### ISSUE TITLE
the armor doesn't show

### ISSUE THREAD

**Issue by thfnhh902** [ElMoha943/ElMoha943-IA_TerrariaPack#16]
**Describe the bug**
the armor doesn't show up when I put it on

**Screenshots**
![2023-02-13_10 47 48](https://user-images.githubusercontent.com/117829663/218366192-78cd5fbe-918b-45ec-a604-21f1559fe0e0.png)
![2023-02-13_10 47 35](https://user-images.githubusercontent.com/117829663/218366238-f19d59a1-4418-48bf-9086-65781b4fa867.png)

**Software Versions (dont say "lastest"):**
- Spigot/Paper Version: 1.19.3
- ItemsAdder Version: 3.3.1
- Lonelibs Version: 1.0.23
- ProtocolLibs Version: Build #612

**Comment by ElMoha943** [comment]
Hello, i would need more information before im able to help you. Please run a /iareload and /iazip and check if there are any errors in console. If so, please reply with a screenshot. I tested with the same setup you have and was able to see the armors, so its probably an error with your installation.
![imagen](https://user-images.githubusercontent.com/25410859/218388328-edb07ebd-63ea-4b4a-9c56-75d359a61552.png)

**Comment by thfnhh902** [comment]
[latest.log](https://github.com/ElMoha943/ElMoha943-IA_TerrariaPack/files/10720157/latest.log)
this is my log
![2023-02-13_15 30 58](https://user-images.githubusercontent.com/117829663/218408985-85f139fb-c0bc-4749-85e4-7934b57e81f2.png)
![2023-02-13_15 31 08](https://user-images.githubusercontent.com/117829663/218409003-31e3e838-4722-47d4-b167-a22544264d15.png)
![Capture](https://user-images.githubusercontent.com/117829663/218410147-b1f41a73-d989-442f-addc-f47d372c1ba0.PNG)
idk bruh armors display red

**Comment by ElMoha943** [comment]
I dont see you runned the commands i asked for in that log, please do so and send me a screenshot of **just that**. Meanwhile you may wanna try removing any visual mods/shadders or other texturepacks you are running that may prevent the armor render to work properly.

**Comment by thfnhh902** [comment]
![Capture](https://user-images.githubusercontent.com/117829663/218944432-e8c5be58-bd81-482c-9b46-061bfaf2bbc4.PNG)
![Capture232323](https://user-images.githubusercontent.com/117829663/218944699-d53611e6-8fcd-4d53-9d1c-2185c0640ab7.PNG)

**Comment by ElMoha943** [comment]
There doesnt seem to be an error with the pack generation. Are you using any other pack apart from mine? if they have the same color that may be a problem. I would also like to know if this error only happens to you or to more people in your server

**Comment by ElMoha943** [comment]
Clossing the ticket as solved for inactivity, feel free to reopen it at any time.

**Comment by thfnhh902** [comment]
what's your itemsadder version?

**Comment by ElMoha943** [comment]
> what's your itemsadder version?

Last test was made on 3.3.1
