### ISSUE TITLE
Doesnt Work with newest ItemsAdder

### ISSUE THREAD

**Issue by Effendil** [ElMoha943/ElMoha943-IA_TerrariaPack#5]
**Describe the bug**

**To Reproduce**
Simply Copy the Main folder into "contents" from ItemsAdder and you see. Nothing happen after /iareload and /iazip

**Expected behavior**
I really expected that it work.

**Screenshots**
Theres nothing to Screenshot

**Software Versions (dont say "lastest"):**
- Spigot/Paper Version: Build 359
- ItemsAdder Version: 3.3.0b-r2

**Additional context**
I try to find a solution by myself and put terraria assets to /resourcepack/assets and not simply into terrariafolder.... but nothing works regardless where the single files go. No Categories or any other stuff work and i dont know why.

**Comment by ElMoha943** [comment]
Hey there, the pack was tested by multiple people and seems to work fine. I will need more information before i can help you further, any errors in console would be helpful.

**Comment by ElMoha943** [comment]
Update: just tested on a local server to make sure, ItemsAdder Version: 3.3.0b-r2 works fine. Probably one of your dependencies is outdated.

Heres my setup:

- paper-1.19.3-362.jar
- ItemsAdder_3.3.0b-r2.jar
- LoneLibs 1.0.22
- ProtocolLib 5.0.0-SNAPSHOT-b608 (lastest dev build)

Closing the ticket now, but feel free to reopen if you need further help.
